/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DeleteAccountModal: typeof import('./src/components/DeleteAccountModal.vue')['default']
    EditVoyageSkeleton: typeof import('./src/components/ui/EditVoyageSkeleton.vue')['default']
    FAQs: typeof import('./src/components/FAQs.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    LogoutModal: typeof import('./src/components/LogoutModal.vue')['default']
    PremiumButton: typeof import('./src/components/ui/PremiumButton.vue')['default']
    PricingCards: typeof import('./src/components/PricingCards.vue')['default']
    Rating: typeof import('./src/components/Rating.vue')['default']
    ReusableButton: typeof import('./src/components/ui/ReusableButton.vue')['default']
    ReusableInput: typeof import('./src/components/ui/ReusableInput.vue')['default']
    ReusableModal: typeof import('./src/components/ui/ReusableModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareModal: typeof import('./src/components/ShareModal.vue')['default']
    SideSlider: typeof import('./src/components/SideSlider.vue')['default']
    SingleVoyageSkeleton: typeof import('./src/components/ui/SingleVoyageSkeleton.vue')['default']
    Spinner: typeof import('./src/components/ui/Spinner.vue')['default']
    ToastContainer: typeof import('./src/components/ui/ToastContainer.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UserModal: typeof import('./src/components/UserModal.vue')['default']
    USkeleton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    UTooltip: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
    VoyagesSkeleton: typeof import('./src/components/ui/VoyagesSkeleton.vue')['default']
  }
}
